---
  tasks:
  - name: Remove old user {{createuser}}
    user: 
      name: {{createuser}}
      state: absent
      remove: {{remove_dir}}
    when: remove_old_user ==  true
    become: yes
  - name: add user {{createuser}}
    user:
      name: {{createuser}}
      shell: /bin/bash
      group: {{createuser}}
      groups: {{user_groups}}
      append: yes
    become: yes
  - name: Set authorized key
    authorized_key:
      user: {{createuser}}
      state: present
      key: "{{ lookup('file', '{{userkey}}'') }}"
      validate: userkey != ""
    when: add_key == true
    become: yes
    become_user: "{{createuser}}"
  - name: Allow user to sudo with out password
    template: 
      src: sudoers.j2
      dest: /etc/sudoers.d/{{createuser}}
      validate: 'visudo -cf %s'
      mode: 0440
    when: enable_passwordless_sudo == true
    become: yes